<?php
/**
 * FieldsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Rossity\PhpQuickbase
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Quick Base API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Rossity\PhpQuickbase;

use \Rossity\PhpQuickbase\Configuration;
use \Rossity\PhpQuickbase\ApiException;
use \Rossity\PhpQuickbase\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FieldsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Rossity\PhpQuickbase
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FieldsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createField
     *
     * Create a field.
     *
     */
    public function testCreateField()
    {
    }

    /**
     * Test case for deleteFields
     *
     * Delete field(s).
     *
     */
    public function testDeleteFields()
    {
    }

    /**
     * Test case for getField
     *
     * Get field.
     *
     */
    public function testGetField()
    {
    }

    /**
     * Test case for getFieldUsage
     *
     * Get usage for a field.
     *
     */
    public function testGetFieldUsage()
    {
    }

    /**
     * Test case for getFields
     *
     * Get fields for a table.
     *
     */
    public function testGetFields()
    {
    }

    /**
     * Test case for getFieldsUsage
     *
     * Get usage for all fields.
     *
     */
    public function testGetFieldsUsage()
    {
    }

    /**
     * Test case for updateField
     *
     * Update a field.
     *
     */
    public function testUpdateField()
    {
    }
}
