<?php
/**
 * FieldsFieldIdProperties
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Rossity\PhpQuickbase
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Quick Base API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Rossity\PhpQuickbase\Model;

use \ArrayAccess;
use \Rossity\PhpQuickbase\ObjectSerializer;

/**
 * FieldsFieldIdProperties Class Doc Comment
 *
 * @category Class
 * @description Specific field properties.
 * @package  Rossity\PhpQuickbase
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class FieldsFieldIdProperties implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_fields__fieldId__properties';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'comments' => 'string',
        'doesTotal' => 'bool',
        'autoSave' => 'bool',
        'defaultValueLuid' => 'int',
        'maxVersions' => 'int',
        'format' => 'int',
        'carryChoices' => 'bool',
        'maxLength' => 'int',
        'linkText' => 'string',
        'parentFieldId' => 'int',
        'displayTimezone' => 'bool',
        'summaryTargetFieldId' => 'int',
        'allowNewChoices' => 'bool',
        'defaultToday' => 'bool',
        'units' => 'string',
        'lookupTargetFieldId' => 'int',
        'summaryFunction' => 'string',
        'sourceFieldId' => 'int',
        'doesAverage' => 'bool',
        'formula' => 'string',
        'decimalPlaces' => 'int',
        'displayMonth' => 'string',
        'seeVersions' => 'bool',
        'numLines' => 'int',
        'defaultKind' => 'string',
        'displayEmail' => 'string',
        'coverText' => 'string',
        'currencySymbol' => 'string',
        'summaryQuery' => 'string',
        'targetFieldId' => 'int',
        'displayUser' => 'string',
        'blankIsZero' => 'bool',
        'exact' => 'bool',
        'defaultDomain' => 'string',
        'defaultValue' => 'string',
        'abbreviate' => 'bool',
        'numberFormat' => 'int',
        'targetTableName' => 'string',
        'appearsAs' => 'string',
        'width' => 'int',
        'currencyFormat' => 'string',
        'displayImages' => 'bool',
        'displayDayOfWeek' => 'bool',
        'summaryReferenceFieldId' => 'int',
        'commaStart' => 'int',
        'choices' => 'string[]',
        'targetTableId' => 'string',
        'displayRelative' => 'bool',
        'compositeFields' => 'string[]',
        'summaryTableId' => 'string',
        'displayTime' => 'bool',
        'versionMode' => 'string',
        'snapFieldId' => 'int',
        'hours24' => 'bool',
        'sortAlpha' => 'bool',
        'sortAsGiven' => 'bool',
        'hasExtension' => 'bool',
        'useNewWindow' => 'bool',
        'appendOnly' => 'bool',
        'displayAsLink' => 'bool',
        'lookupReferenceFieldId' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'comments' => null,
        'doesTotal' => null,
        'autoSave' => null,
        'defaultValueLuid' => null,
        'maxVersions' => 'int32',
        'format' => null,
        'carryChoices' => null,
        'maxLength' => null,
        'linkText' => null,
        'parentFieldId' => null,
        'displayTimezone' => null,
        'summaryTargetFieldId' => null,
        'allowNewChoices' => null,
        'defaultToday' => null,
        'units' => null,
        'lookupTargetFieldId' => null,
        'summaryFunction' => null,
        'sourceFieldId' => null,
        'doesAverage' => null,
        'formula' => null,
        'decimalPlaces' => null,
        'displayMonth' => null,
        'seeVersions' => null,
        'numLines' => null,
        'defaultKind' => null,
        'displayEmail' => null,
        'coverText' => null,
        'currencySymbol' => null,
        'summaryQuery' => null,
        'targetFieldId' => null,
        'displayUser' => null,
        'blankIsZero' => null,
        'exact' => null,
        'defaultDomain' => null,
        'defaultValue' => null,
        'abbreviate' => null,
        'numberFormat' => null,
        'targetTableName' => null,
        'appearsAs' => null,
        'width' => null,
        'currencyFormat' => null,
        'displayImages' => null,
        'displayDayOfWeek' => null,
        'summaryReferenceFieldId' => null,
        'commaStart' => null,
        'choices' => null,
        'targetTableId' => null,
        'displayRelative' => null,
        'compositeFields' => null,
        'summaryTableId' => null,
        'displayTime' => null,
        'versionMode' => null,
        'snapFieldId' => null,
        'hours24' => null,
        'sortAlpha' => null,
        'sortAsGiven' => null,
        'hasExtension' => null,
        'useNewWindow' => null,
        'appendOnly' => null,
        'displayAsLink' => null,
        'lookupReferenceFieldId' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'comments' => 'comments',
        'doesTotal' => 'doesTotal',
        'autoSave' => 'autoSave',
        'defaultValueLuid' => 'defaultValueLuid',
        'maxVersions' => 'maxVersions',
        'format' => 'format',
        'carryChoices' => 'carryChoices',
        'maxLength' => 'maxLength',
        'linkText' => 'linkText',
        'parentFieldId' => 'parentFieldId',
        'displayTimezone' => 'displayTimezone',
        'summaryTargetFieldId' => 'summaryTargetFieldId',
        'allowNewChoices' => 'allowNewChoices',
        'defaultToday' => 'defaultToday',
        'units' => 'units',
        'lookupTargetFieldId' => 'lookupTargetFieldId',
        'summaryFunction' => 'summaryFunction',
        'sourceFieldId' => 'sourceFieldId',
        'doesAverage' => 'doesAverage',
        'formula' => 'formula',
        'decimalPlaces' => 'decimalPlaces',
        'displayMonth' => 'displayMonth',
        'seeVersions' => 'seeVersions',
        'numLines' => 'numLines',
        'defaultKind' => 'defaultKind',
        'displayEmail' => 'displayEmail',
        'coverText' => 'coverText',
        'currencySymbol' => 'currencySymbol',
        'summaryQuery' => 'summaryQuery',
        'targetFieldId' => 'targetFieldId',
        'displayUser' => 'displayUser',
        'blankIsZero' => 'blankIsZero',
        'exact' => 'exact',
        'defaultDomain' => 'defaultDomain',
        'defaultValue' => 'defaultValue',
        'abbreviate' => 'abbreviate',
        'numberFormat' => 'numberFormat',
        'targetTableName' => 'targetTableName',
        'appearsAs' => 'appearsAs',
        'width' => 'width',
        'currencyFormat' => 'currencyFormat',
        'displayImages' => 'displayImages',
        'displayDayOfWeek' => 'displayDayOfWeek',
        'summaryReferenceFieldId' => 'summaryReferenceFieldId',
        'commaStart' => 'commaStart',
        'choices' => 'choices',
        'targetTableId' => 'targetTableId',
        'displayRelative' => 'displayRelative',
        'compositeFields' => 'compositeFields',
        'summaryTableId' => 'summaryTableId',
        'displayTime' => 'displayTime',
        'versionMode' => 'versionMode',
        'snapFieldId' => 'snapFieldId',
        'hours24' => 'hours24',
        'sortAlpha' => 'sortAlpha',
        'sortAsGiven' => 'sortAsGiven',
        'hasExtension' => 'hasExtension',
        'useNewWindow' => 'useNewWindow',
        'appendOnly' => 'appendOnly',
        'displayAsLink' => 'displayAsLink',
        'lookupReferenceFieldId' => 'lookupReferenceFieldId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'comments' => 'setComments',
        'doesTotal' => 'setDoesTotal',
        'autoSave' => 'setAutoSave',
        'defaultValueLuid' => 'setDefaultValueLuid',
        'maxVersions' => 'setMaxVersions',
        'format' => 'setFormat',
        'carryChoices' => 'setCarryChoices',
        'maxLength' => 'setMaxLength',
        'linkText' => 'setLinkText',
        'parentFieldId' => 'setParentFieldId',
        'displayTimezone' => 'setDisplayTimezone',
        'summaryTargetFieldId' => 'setSummaryTargetFieldId',
        'allowNewChoices' => 'setAllowNewChoices',
        'defaultToday' => 'setDefaultToday',
        'units' => 'setUnits',
        'lookupTargetFieldId' => 'setLookupTargetFieldId',
        'summaryFunction' => 'setSummaryFunction',
        'sourceFieldId' => 'setSourceFieldId',
        'doesAverage' => 'setDoesAverage',
        'formula' => 'setFormula',
        'decimalPlaces' => 'setDecimalPlaces',
        'displayMonth' => 'setDisplayMonth',
        'seeVersions' => 'setSeeVersions',
        'numLines' => 'setNumLines',
        'defaultKind' => 'setDefaultKind',
        'displayEmail' => 'setDisplayEmail',
        'coverText' => 'setCoverText',
        'currencySymbol' => 'setCurrencySymbol',
        'summaryQuery' => 'setSummaryQuery',
        'targetFieldId' => 'setTargetFieldId',
        'displayUser' => 'setDisplayUser',
        'blankIsZero' => 'setBlankIsZero',
        'exact' => 'setExact',
        'defaultDomain' => 'setDefaultDomain',
        'defaultValue' => 'setDefaultValue',
        'abbreviate' => 'setAbbreviate',
        'numberFormat' => 'setNumberFormat',
        'targetTableName' => 'setTargetTableName',
        'appearsAs' => 'setAppearsAs',
        'width' => 'setWidth',
        'currencyFormat' => 'setCurrencyFormat',
        'displayImages' => 'setDisplayImages',
        'displayDayOfWeek' => 'setDisplayDayOfWeek',
        'summaryReferenceFieldId' => 'setSummaryReferenceFieldId',
        'commaStart' => 'setCommaStart',
        'choices' => 'setChoices',
        'targetTableId' => 'setTargetTableId',
        'displayRelative' => 'setDisplayRelative',
        'compositeFields' => 'setCompositeFields',
        'summaryTableId' => 'setSummaryTableId',
        'displayTime' => 'setDisplayTime',
        'versionMode' => 'setVersionMode',
        'snapFieldId' => 'setSnapFieldId',
        'hours24' => 'setHours24',
        'sortAlpha' => 'setSortAlpha',
        'sortAsGiven' => 'setSortAsGiven',
        'hasExtension' => 'setHasExtension',
        'useNewWindow' => 'setUseNewWindow',
        'appendOnly' => 'setAppendOnly',
        'displayAsLink' => 'setDisplayAsLink',
        'lookupReferenceFieldId' => 'setLookupReferenceFieldId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'comments' => 'getComments',
        'doesTotal' => 'getDoesTotal',
        'autoSave' => 'getAutoSave',
        'defaultValueLuid' => 'getDefaultValueLuid',
        'maxVersions' => 'getMaxVersions',
        'format' => 'getFormat',
        'carryChoices' => 'getCarryChoices',
        'maxLength' => 'getMaxLength',
        'linkText' => 'getLinkText',
        'parentFieldId' => 'getParentFieldId',
        'displayTimezone' => 'getDisplayTimezone',
        'summaryTargetFieldId' => 'getSummaryTargetFieldId',
        'allowNewChoices' => 'getAllowNewChoices',
        'defaultToday' => 'getDefaultToday',
        'units' => 'getUnits',
        'lookupTargetFieldId' => 'getLookupTargetFieldId',
        'summaryFunction' => 'getSummaryFunction',
        'sourceFieldId' => 'getSourceFieldId',
        'doesAverage' => 'getDoesAverage',
        'formula' => 'getFormula',
        'decimalPlaces' => 'getDecimalPlaces',
        'displayMonth' => 'getDisplayMonth',
        'seeVersions' => 'getSeeVersions',
        'numLines' => 'getNumLines',
        'defaultKind' => 'getDefaultKind',
        'displayEmail' => 'getDisplayEmail',
        'coverText' => 'getCoverText',
        'currencySymbol' => 'getCurrencySymbol',
        'summaryQuery' => 'getSummaryQuery',
        'targetFieldId' => 'getTargetFieldId',
        'displayUser' => 'getDisplayUser',
        'blankIsZero' => 'getBlankIsZero',
        'exact' => 'getExact',
        'defaultDomain' => 'getDefaultDomain',
        'defaultValue' => 'getDefaultValue',
        'abbreviate' => 'getAbbreviate',
        'numberFormat' => 'getNumberFormat',
        'targetTableName' => 'getTargetTableName',
        'appearsAs' => 'getAppearsAs',
        'width' => 'getWidth',
        'currencyFormat' => 'getCurrencyFormat',
        'displayImages' => 'getDisplayImages',
        'displayDayOfWeek' => 'getDisplayDayOfWeek',
        'summaryReferenceFieldId' => 'getSummaryReferenceFieldId',
        'commaStart' => 'getCommaStart',
        'choices' => 'getChoices',
        'targetTableId' => 'getTargetTableId',
        'displayRelative' => 'getDisplayRelative',
        'compositeFields' => 'getCompositeFields',
        'summaryTableId' => 'getSummaryTableId',
        'displayTime' => 'getDisplayTime',
        'versionMode' => 'getVersionMode',
        'snapFieldId' => 'getSnapFieldId',
        'hours24' => 'getHours24',
        'sortAlpha' => 'getSortAlpha',
        'sortAsGiven' => 'getSortAsGiven',
        'hasExtension' => 'getHasExtension',
        'useNewWindow' => 'getUseNewWindow',
        'appendOnly' => 'getAppendOnly',
        'displayAsLink' => 'getDisplayAsLink',
        'lookupReferenceFieldId' => 'getLookupReferenceFieldId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const SUMMARY_FUNCTION_AVG = 'AVG';
    const SUMMARY_FUNCTION_SUM = 'SUM';
    const SUMMARY_FUNCTION_MAX = 'MAX';
    const SUMMARY_FUNCTION_MIN = 'MIN';
    const SUMMARY_FUNCTION_STD_DEV = 'STD-DEV';
    const SUMMARY_FUNCTION_COUNT = 'COUNT';
    const SUMMARY_FUNCTION_COMBINED_TEXT = 'COMBINED-TEXT';
    const SUMMARY_FUNCTION_DISTINCT_COUNT = 'DISTINCT-COUNT';
    const VERSION_MODE_KEEPALLVERSIONS = 'keepallversions';
    const VERSION_MODE_KEEPLASTVERSIONS = 'keeplastversions';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSummaryFunctionAllowableValues()
    {
        return [
            self::SUMMARY_FUNCTION_AVG,
            self::SUMMARY_FUNCTION_SUM,
            self::SUMMARY_FUNCTION_MAX,
            self::SUMMARY_FUNCTION_MIN,
            self::SUMMARY_FUNCTION_STD_DEV,
            self::SUMMARY_FUNCTION_COUNT,
            self::SUMMARY_FUNCTION_COMBINED_TEXT,
            self::SUMMARY_FUNCTION_DISTINCT_COUNT,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getVersionModeAllowableValues()
    {
        return [
            self::VERSION_MODE_KEEPALLVERSIONS,
            self::VERSION_MODE_KEEPLASTVERSIONS,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['comments'] = $data['comments'] ?? null;
        $this->container['doesTotal'] = $data['doesTotal'] ?? null;
        $this->container['autoSave'] = $data['autoSave'] ?? null;
        $this->container['defaultValueLuid'] = $data['defaultValueLuid'] ?? null;
        $this->container['maxVersions'] = $data['maxVersions'] ?? null;
        $this->container['format'] = $data['format'] ?? null;
        $this->container['carryChoices'] = $data['carryChoices'] ?? null;
        $this->container['maxLength'] = $data['maxLength'] ?? null;
        $this->container['linkText'] = $data['linkText'] ?? null;
        $this->container['parentFieldId'] = $data['parentFieldId'] ?? null;
        $this->container['displayTimezone'] = $data['displayTimezone'] ?? null;
        $this->container['summaryTargetFieldId'] = $data['summaryTargetFieldId'] ?? null;
        $this->container['allowNewChoices'] = $data['allowNewChoices'] ?? null;
        $this->container['defaultToday'] = $data['defaultToday'] ?? null;
        $this->container['units'] = $data['units'] ?? null;
        $this->container['lookupTargetFieldId'] = $data['lookupTargetFieldId'] ?? null;
        $this->container['summaryFunction'] = $data['summaryFunction'] ?? null;
        $this->container['sourceFieldId'] = $data['sourceFieldId'] ?? null;
        $this->container['doesAverage'] = $data['doesAverage'] ?? null;
        $this->container['formula'] = $data['formula'] ?? null;
        $this->container['decimalPlaces'] = $data['decimalPlaces'] ?? null;
        $this->container['displayMonth'] = $data['displayMonth'] ?? null;
        $this->container['seeVersions'] = $data['seeVersions'] ?? null;
        $this->container['numLines'] = $data['numLines'] ?? null;
        $this->container['defaultKind'] = $data['defaultKind'] ?? null;
        $this->container['displayEmail'] = $data['displayEmail'] ?? null;
        $this->container['coverText'] = $data['coverText'] ?? null;
        $this->container['currencySymbol'] = $data['currencySymbol'] ?? null;
        $this->container['summaryQuery'] = $data['summaryQuery'] ?? null;
        $this->container['targetFieldId'] = $data['targetFieldId'] ?? null;
        $this->container['displayUser'] = $data['displayUser'] ?? null;
        $this->container['blankIsZero'] = $data['blankIsZero'] ?? null;
        $this->container['exact'] = $data['exact'] ?? null;
        $this->container['defaultDomain'] = $data['defaultDomain'] ?? null;
        $this->container['defaultValue'] = $data['defaultValue'] ?? null;
        $this->container['abbreviate'] = $data['abbreviate'] ?? null;
        $this->container['numberFormat'] = $data['numberFormat'] ?? null;
        $this->container['targetTableName'] = $data['targetTableName'] ?? null;
        $this->container['appearsAs'] = $data['appearsAs'] ?? null;
        $this->container['width'] = $data['width'] ?? null;
        $this->container['currencyFormat'] = $data['currencyFormat'] ?? null;
        $this->container['displayImages'] = $data['displayImages'] ?? null;
        $this->container['displayDayOfWeek'] = $data['displayDayOfWeek'] ?? null;
        $this->container['summaryReferenceFieldId'] = $data['summaryReferenceFieldId'] ?? null;
        $this->container['commaStart'] = $data['commaStart'] ?? null;
        $this->container['choices'] = $data['choices'] ?? null;
        $this->container['targetTableId'] = $data['targetTableId'] ?? null;
        $this->container['displayRelative'] = $data['displayRelative'] ?? null;
        $this->container['compositeFields'] = $data['compositeFields'] ?? null;
        $this->container['summaryTableId'] = $data['summaryTableId'] ?? null;
        $this->container['displayTime'] = $data['displayTime'] ?? null;
        $this->container['versionMode'] = $data['versionMode'] ?? null;
        $this->container['snapFieldId'] = $data['snapFieldId'] ?? null;
        $this->container['hours24'] = $data['hours24'] ?? null;
        $this->container['sortAlpha'] = $data['sortAlpha'] ?? null;
        $this->container['sortAsGiven'] = $data['sortAsGiven'] ?? null;
        $this->container['hasExtension'] = $data['hasExtension'] ?? null;
        $this->container['useNewWindow'] = $data['useNewWindow'] ?? null;
        $this->container['appendOnly'] = $data['appendOnly'] ?? null;
        $this->container['displayAsLink'] = $data['displayAsLink'] ?? null;
        $this->container['lookupReferenceFieldId'] = $data['lookupReferenceFieldId'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['maxVersions']) && ($this->container['maxVersions'] < 1)) {
            $invalidProperties[] = "invalid value for 'maxVersions', must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getSummaryFunctionAllowableValues();
        if (!is_null($this->container['summaryFunction']) && !in_array($this->container['summaryFunction'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'summaryFunction', must be one of '%s'",
                $this->container['summaryFunction'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getVersionModeAllowableValues();
        if (!is_null($this->container['versionMode']) && !in_array($this->container['versionMode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'versionMode', must be one of '%s'",
                $this->container['versionMode'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets comments
     *
     * @return string|null
     */
    public function getComments()
    {
        return $this->container['comments'];
    }

    /**
     * Sets comments
     *
     * @param string|null $comments The comments entered on the field properties by an administrator.
     *
     * @return self
     */
    public function setComments($comments)
    {
        $this->container['comments'] = $comments;

        return $this;
    }

    /**
     * Gets doesTotal
     *
     * @return bool|null
     */
    public function getDoesTotal()
    {
        return $this->container['doesTotal'];
    }

    /**
     * Sets doesTotal
     *
     * @param bool|null $doesTotal Whether this field totals in reports within the product.
     *
     * @return self
     */
    public function setDoesTotal($doesTotal)
    {
        $this->container['doesTotal'] = $doesTotal;

        return $this;
    }

    /**
     * Gets autoSave
     *
     * @return bool|null
     */
    public function getAutoSave()
    {
        return $this->container['autoSave'];
    }

    /**
     * Sets autoSave
     *
     * @param bool|null $autoSave Whether the link field will auto save.
     *
     * @return self
     */
    public function setAutoSave($autoSave)
    {
        $this->container['autoSave'] = $autoSave;

        return $this;
    }

    /**
     * Gets defaultValueLuid
     *
     * @return int|null
     */
    public function getDefaultValueLuid()
    {
        return $this->container['defaultValueLuid'];
    }

    /**
     * Sets defaultValueLuid
     *
     * @param int|null $defaultValueLuid Default user id value.
     *
     * @return self
     */
    public function setDefaultValueLuid($defaultValueLuid)
    {
        $this->container['defaultValueLuid'] = $defaultValueLuid;

        return $this;
    }

    /**
     * Gets maxVersions
     *
     * @return int|null
     */
    public function getMaxVersions()
    {
        return $this->container['maxVersions'];
    }

    /**
     * Sets maxVersions
     *
     * @param int|null $maxVersions The maximum number of versions configured for a file attachment.
     *
     * @return self
     */
    public function setMaxVersions($maxVersions)
    {

        if (!is_null($maxVersions) && ($maxVersions < 1)) {
            throw new \InvalidArgumentException('invalid value for $maxVersions when calling FieldsFieldIdProperties., must be bigger than or equal to 1.');
        }

        $this->container['maxVersions'] = $maxVersions;

        return $this;
    }

    /**
     * Gets format
     *
     * @return int|null
     */
    public function getFormat()
    {
        return $this->container['format'];
    }

    /**
     * Sets format
     *
     * @param int|null $format The format to display time.
     *
     * @return self
     */
    public function setFormat($format)
    {
        $this->container['format'] = $format;

        return $this;
    }

    /**
     * Gets carryChoices
     *
     * @return bool|null
     */
    public function getCarryChoices()
    {
        return $this->container['carryChoices'];
    }

    /**
     * Sets carryChoices
     *
     * @param bool|null $carryChoices Whether the field should carry its multiple choice fields when copied.
     *
     * @return self
     */
    public function setCarryChoices($carryChoices)
    {
        $this->container['carryChoices'] = $carryChoices;

        return $this;
    }

    /**
     * Gets maxLength
     *
     * @return int|null
     */
    public function getMaxLength()
    {
        return $this->container['maxLength'];
    }

    /**
     * Sets maxLength
     *
     * @param int|null $maxLength The maximum number of characters allowed for entry in the Quick Base product for this field.
     *
     * @return self
     */
    public function setMaxLength($maxLength)
    {
        $this->container['maxLength'] = $maxLength;

        return $this;
    }

    /**
     * Gets linkText
     *
     * @return string|null
     */
    public function getLinkText()
    {
        return $this->container['linkText'];
    }

    /**
     * Sets linkText
     *
     * @param string|null $linkText The configured text value that replaces the URL that users see within the product.
     *
     * @return self
     */
    public function setLinkText($linkText)
    {
        $this->container['linkText'] = $linkText;

        return $this;
    }

    /**
     * Gets parentFieldId
     *
     * @return int|null
     */
    public function getParentFieldId()
    {
        return $this->container['parentFieldId'];
    }

    /**
     * Sets parentFieldId
     *
     * @param int|null $parentFieldId The id of the parent composite field, when applicable.
     *
     * @return self
     */
    public function setParentFieldId($parentFieldId)
    {
        $this->container['parentFieldId'] = $parentFieldId;

        return $this;
    }

    /**
     * Gets displayTimezone
     *
     * @return bool|null
     */
    public function getDisplayTimezone()
    {
        return $this->container['displayTimezone'];
    }

    /**
     * Sets displayTimezone
     *
     * @param bool|null $displayTimezone Indicates whether to display the timezone within the product.
     *
     * @return self
     */
    public function setDisplayTimezone($displayTimezone)
    {
        $this->container['displayTimezone'] = $displayTimezone;

        return $this;
    }

    /**
     * Gets summaryTargetFieldId
     *
     * @return int|null
     */
    public function getSummaryTargetFieldId()
    {
        return $this->container['summaryTargetFieldId'];
    }

    /**
     * Sets summaryTargetFieldId
     *
     * @param int|null $summaryTargetFieldId The id of the field that is used to aggregate values from the child, when applicable. This displays 0 if the summary function doesn’t require a field selection (like count).
     *
     * @return self
     */
    public function setSummaryTargetFieldId($summaryTargetFieldId)
    {
        $this->container['summaryTargetFieldId'] = $summaryTargetFieldId;

        return $this;
    }

    /**
     * Gets allowNewChoices
     *
     * @return bool|null
     */
    public function getAllowNewChoices()
    {
        return $this->container['allowNewChoices'];
    }

    /**
     * Sets allowNewChoices
     *
     * @param bool|null $allowNewChoices Indicates if users can add new choices to a selection list.
     *
     * @return self
     */
    public function setAllowNewChoices($allowNewChoices)
    {
        $this->container['allowNewChoices'] = $allowNewChoices;

        return $this;
    }

    /**
     * Gets defaultToday
     *
     * @return bool|null
     */
    public function getDefaultToday()
    {
        return $this->container['defaultToday'];
    }

    /**
     * Sets defaultToday
     *
     * @param bool|null $defaultToday Indicates if the field value is defaulted today for new records.
     *
     * @return self
     */
    public function setDefaultToday($defaultToday)
    {
        $this->container['defaultToday'] = $defaultToday;

        return $this;
    }

    /**
     * Gets units
     *
     * @return string|null
     */
    public function getUnits()
    {
        return $this->container['units'];
    }

    /**
     * Sets units
     *
     * @param string|null $units The units label.
     *
     * @return self
     */
    public function setUnits($units)
    {
        $this->container['units'] = $units;

        return $this;
    }

    /**
     * Gets lookupTargetFieldId
     *
     * @return int|null
     */
    public function getLookupTargetFieldId()
    {
        return $this->container['lookupTargetFieldId'];
    }

    /**
     * Sets lookupTargetFieldId
     *
     * @param int|null $lookupTargetFieldId The id of the field that is the target on the parent table for this lookup.
     *
     * @return self
     */
    public function setLookupTargetFieldId($lookupTargetFieldId)
    {
        $this->container['lookupTargetFieldId'] = $lookupTargetFieldId;

        return $this;
    }

    /**
     * Gets summaryFunction
     *
     * @return string|null
     */
    public function getSummaryFunction()
    {
        return $this->container['summaryFunction'];
    }

    /**
     * Sets summaryFunction
     *
     * @param string|null $summaryFunction The accumulation type for the summary field.
     *
     * @return self
     */
    public function setSummaryFunction($summaryFunction)
    {
        $allowedValues = $this->getSummaryFunctionAllowableValues();
        if (!is_null($summaryFunction) && !in_array($summaryFunction, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'summaryFunction', must be one of '%s'",
                    $summaryFunction,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['summaryFunction'] = $summaryFunction;

        return $this;
    }

    /**
     * Gets sourceFieldId
     *
     * @return int|null
     */
    public function getSourceFieldId()
    {
        return $this->container['sourceFieldId'];
    }

    /**
     * Sets sourceFieldId
     *
     * @param int|null $sourceFieldId The id of the source field.
     *
     * @return self
     */
    public function setSourceFieldId($sourceFieldId)
    {
        $this->container['sourceFieldId'] = $sourceFieldId;

        return $this;
    }

    /**
     * Gets doesAverage
     *
     * @return bool|null
     */
    public function getDoesAverage()
    {
        return $this->container['doesAverage'];
    }

    /**
     * Sets doesAverage
     *
     * @param bool|null $doesAverage Whether this field averages in reports within the product.
     *
     * @return self
     */
    public function setDoesAverage($doesAverage)
    {
        $this->container['doesAverage'] = $doesAverage;

        return $this;
    }

    /**
     * Gets formula
     *
     * @return string|null
     */
    public function getFormula()
    {
        return $this->container['formula'];
    }

    /**
     * Sets formula
     *
     * @param string|null $formula The formula of the field as configured in Quick Base.
     *
     * @return self
     */
    public function setFormula($formula)
    {
        $this->container['formula'] = $formula;

        return $this;
    }

    /**
     * Gets decimalPlaces
     *
     * @return int|null
     */
    public function getDecimalPlaces()
    {
        return $this->container['decimalPlaces'];
    }

    /**
     * Sets decimalPlaces
     *
     * @param int|null $decimalPlaces The number of decimal places displayed in the product for this field.
     *
     * @return self
     */
    public function setDecimalPlaces($decimalPlaces)
    {
        $this->container['decimalPlaces'] = $decimalPlaces;

        return $this;
    }

    /**
     * Gets displayMonth
     *
     * @return string|null
     */
    public function getDisplayMonth()
    {
        return $this->container['displayMonth'];
    }

    /**
     * Sets displayMonth
     *
     * @param string|null $displayMonth How to display months.
     *
     * @return self
     */
    public function setDisplayMonth($displayMonth)
    {
        $this->container['displayMonth'] = $displayMonth;

        return $this;
    }

    /**
     * Gets seeVersions
     *
     * @return bool|null
     */
    public function getSeeVersions()
    {
        return $this->container['seeVersions'];
    }

    /**
     * Sets seeVersions
     *
     * @param bool|null $seeVersions Indicates if the user can see other versions, aside from the most recent, of a file attachment within the product.
     *
     * @return self
     */
    public function setSeeVersions($seeVersions)
    {
        $this->container['seeVersions'] = $seeVersions;

        return $this;
    }

    /**
     * Gets numLines
     *
     * @return int|null
     */
    public function getNumLines()
    {
        return $this->container['numLines'];
    }

    /**
     * Sets numLines
     *
     * @param int|null $numLines The number of lines shown in the Quick Base product for this text field.
     *
     * @return self
     */
    public function setNumLines($numLines)
    {
        $this->container['numLines'] = $numLines;

        return $this;
    }

    /**
     * Gets defaultKind
     *
     * @return string|null
     */
    public function getDefaultKind()
    {
        return $this->container['defaultKind'];
    }

    /**
     * Sets defaultKind
     *
     * @param string|null $defaultKind The user default type.
     *
     * @return self
     */
    public function setDefaultKind($defaultKind)
    {
        $this->container['defaultKind'] = $defaultKind;

        return $this;
    }

    /**
     * Gets displayEmail
     *
     * @return string|null
     */
    public function getDisplayEmail()
    {
        return $this->container['displayEmail'];
    }

    /**
     * Sets displayEmail
     *
     * @param string|null $displayEmail How the email is displayed.
     *
     * @return self
     */
    public function setDisplayEmail($displayEmail)
    {
        $this->container['displayEmail'] = $displayEmail;

        return $this;
    }

    /**
     * Gets coverText
     *
     * @return string|null
     */
    public function getCoverText()
    {
        return $this->container['coverText'];
    }

    /**
     * Sets coverText
     *
     * @param string|null $coverText An alternate user friendly text that can be used to display a link in the browser.
     *
     * @return self
     */
    public function setCoverText($coverText)
    {
        $this->container['coverText'] = $coverText;

        return $this;
    }

    /**
     * Gets currencySymbol
     *
     * @return string|null
     */
    public function getCurrencySymbol()
    {
        return $this->container['currencySymbol'];
    }

    /**
     * Sets currencySymbol
     *
     * @param string|null $currencySymbol The current symbol used when displaying field values within the product.
     *
     * @return self
     */
    public function setCurrencySymbol($currencySymbol)
    {
        $this->container['currencySymbol'] = $currencySymbol;

        return $this;
    }

    /**
     * Gets summaryQuery
     *
     * @return string|null
     */
    public function getSummaryQuery()
    {
        return $this->container['summaryQuery'];
    }

    /**
     * Sets summaryQuery
     *
     * @param string|null $summaryQuery The summary query.
     *
     * @return self
     */
    public function setSummaryQuery($summaryQuery)
    {
        $this->container['summaryQuery'] = $summaryQuery;

        return $this;
    }

    /**
     * Gets targetFieldId
     *
     * @return int|null
     */
    public function getTargetFieldId()
    {
        return $this->container['targetFieldId'];
    }

    /**
     * Sets targetFieldId
     *
     * @param int|null $targetFieldId The id of the target field.
     *
     * @return self
     */
    public function setTargetFieldId($targetFieldId)
    {
        $this->container['targetFieldId'] = $targetFieldId;

        return $this;
    }

    /**
     * Gets displayUser
     *
     * @return string|null
     */
    public function getDisplayUser()
    {
        return $this->container['displayUser'];
    }

    /**
     * Sets displayUser
     *
     * @param string|null $displayUser The configured option for how users display within the product.
     *
     * @return self
     */
    public function setDisplayUser($displayUser)
    {
        $this->container['displayUser'] = $displayUser;

        return $this;
    }

    /**
     * Gets blankIsZero
     *
     * @return bool|null
     */
    public function getBlankIsZero()
    {
        return $this->container['blankIsZero'];
    }

    /**
     * Sets blankIsZero
     *
     * @param bool|null $blankIsZero Whether a blank value is treated the same as 0 in calculations within the product.
     *
     * @return self
     */
    public function setBlankIsZero($blankIsZero)
    {
        $this->container['blankIsZero'] = $blankIsZero;

        return $this;
    }

    /**
     * Gets exact
     *
     * @return bool|null
     */
    public function getExact()
    {
        return $this->container['exact'];
    }

    /**
     * Sets exact
     *
     * @param bool|null $exact Whether an exact match is required for a report link.
     *
     * @return self
     */
    public function setExact($exact)
    {
        $this->container['exact'] = $exact;

        return $this;
    }

    /**
     * Gets defaultDomain
     *
     * @return string|null
     */
    public function getDefaultDomain()
    {
        return $this->container['defaultDomain'];
    }

    /**
     * Sets defaultDomain
     *
     * @param string|null $defaultDomain Default email domain.
     *
     * @return self
     */
    public function setDefaultDomain($defaultDomain)
    {
        $this->container['defaultDomain'] = $defaultDomain;

        return $this;
    }

    /**
     * Gets defaultValue
     *
     * @return string|null
     */
    public function getDefaultValue()
    {
        return $this->container['defaultValue'];
    }

    /**
     * Sets defaultValue
     *
     * @param string|null $defaultValue The default value configured for a field when a new record is added.
     *
     * @return self
     */
    public function setDefaultValue($defaultValue)
    {
        $this->container['defaultValue'] = $defaultValue;

        return $this;
    }

    /**
     * Gets abbreviate
     *
     * @return bool|null
     */
    public function getAbbreviate()
    {
        return $this->container['abbreviate'];
    }

    /**
     * Sets abbreviate
     *
     * @param bool|null $abbreviate Don't show the URL protocol when showing the URL.
     *
     * @return self
     */
    public function setAbbreviate($abbreviate)
    {
        $this->container['abbreviate'] = $abbreviate;

        return $this;
    }

    /**
     * Gets numberFormat
     *
     * @return int|null
     */
    public function getNumberFormat()
    {
        return $this->container['numberFormat'];
    }

    /**
     * Sets numberFormat
     *
     * @param int|null $numberFormat The format used for displaying numeric values in the product (decimal, separators, digit group).
     *
     * @return self
     */
    public function setNumberFormat($numberFormat)
    {
        $this->container['numberFormat'] = $numberFormat;

        return $this;
    }

    /**
     * Gets targetTableName
     *
     * @return string|null
     */
    public function getTargetTableName()
    {
        return $this->container['targetTableName'];
    }

    /**
     * Sets targetTableName
     *
     * @param string|null $targetTableName The field's target table name.
     *
     * @return self
     */
    public function setTargetTableName($targetTableName)
    {
        $this->container['targetTableName'] = $targetTableName;

        return $this;
    }

    /**
     * Gets appearsAs
     *
     * @return string|null
     */
    public function getAppearsAs()
    {
        return $this->container['appearsAs'];
    }

    /**
     * Sets appearsAs
     *
     * @param string|null $appearsAs The link text, if empty, the url will be used as link text.
     *
     * @return self
     */
    public function setAppearsAs($appearsAs)
    {
        $this->container['appearsAs'] = $appearsAs;

        return $this;
    }

    /**
     * Gets width
     *
     * @return int|null
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     *
     * @param int|null $width The field's html input width in the product.
     *
     * @return self
     */
    public function setWidth($width)
    {
        $this->container['width'] = $width;

        return $this;
    }

    /**
     * Gets currencyFormat
     *
     * @return string|null
     */
    public function getCurrencyFormat()
    {
        return $this->container['currencyFormat'];
    }

    /**
     * Sets currencyFormat
     *
     * @param string|null $currencyFormat The currency format used when displaying field values within the product.
     *
     * @return self
     */
    public function setCurrencyFormat($currencyFormat)
    {
        $this->container['currencyFormat'] = $currencyFormat;

        return $this;
    }

    /**
     * Gets displayImages
     *
     * @return bool|null
     */
    public function getDisplayImages()
    {
        return $this->container['displayImages'];
    }

    /**
     * Sets displayImages
     *
     * @param bool|null $displayImages Indicates whether images will display for file attachments on forms and reports within the product.
     *
     * @return self
     */
    public function setDisplayImages($displayImages)
    {
        $this->container['displayImages'] = $displayImages;

        return $this;
    }

    /**
     * Gets displayDayOfWeek
     *
     * @return bool|null
     */
    public function getDisplayDayOfWeek()
    {
        return $this->container['displayDayOfWeek'];
    }

    /**
     * Sets displayDayOfWeek
     *
     * @param bool|null $displayDayOfWeek Indicates whether to display the day of the week within the product.
     *
     * @return self
     */
    public function setDisplayDayOfWeek($displayDayOfWeek)
    {
        $this->container['displayDayOfWeek'] = $displayDayOfWeek;

        return $this;
    }

    /**
     * Gets summaryReferenceFieldId
     *
     * @return int|null
     */
    public function getSummaryReferenceFieldId()
    {
        return $this->container['summaryReferenceFieldId'];
    }

    /**
     * Sets summaryReferenceFieldId
     *
     * @param int|null $summaryReferenceFieldId The id of the field that is the reference in the relationship for this summary.
     *
     * @return self
     */
    public function setSummaryReferenceFieldId($summaryReferenceFieldId)
    {
        $this->container['summaryReferenceFieldId'] = $summaryReferenceFieldId;

        return $this;
    }

    /**
     * Gets commaStart
     *
     * @return int|null
     */
    public function getCommaStart()
    {
        return $this->container['commaStart'];
    }

    /**
     * Sets commaStart
     *
     * @param int|null $commaStart The number of digits before commas display in the product, when applicable.
     *
     * @return self
     */
    public function setCommaStart($commaStart)
    {
        $this->container['commaStart'] = $commaStart;

        return $this;
    }

    /**
     * Gets choices
     *
     * @return string[]|null
     */
    public function getChoices()
    {
        return $this->container['choices'];
    }

    /**
     * Sets choices
     *
     * @param string[]|null $choices An array of entries that exist for a field that offers choices to the user. Note that these choices refer to the valid values of any records added in the future. You are allowed to remove values from the list of choices even if there are existing records with those values in this field. They will be displayed in red when users look at the data in the browser but there is no other effect. While updating a field with this property, the old choices are removed and replaced by the new choices.
     *
     * @return self
     */
    public function setChoices($choices)
    {
        $this->container['choices'] = $choices;

        return $this;
    }

    /**
     * Gets targetTableId
     *
     * @return string|null
     */
    public function getTargetTableId()
    {
        return $this->container['targetTableId'];
    }

    /**
     * Sets targetTableId
     *
     * @param string|null $targetTableId The id of the target table.
     *
     * @return self
     */
    public function setTargetTableId($targetTableId)
    {
        $this->container['targetTableId'] = $targetTableId;

        return $this;
    }

    /**
     * Gets displayRelative
     *
     * @return bool|null
     */
    public function getDisplayRelative()
    {
        return $this->container['displayRelative'];
    }

    /**
     * Sets displayRelative
     *
     * @param bool|null $displayRelative Whether to display time as relative.
     *
     * @return self
     */
    public function setDisplayRelative($displayRelative)
    {
        $this->container['displayRelative'] = $displayRelative;

        return $this;
    }

    /**
     * Gets compositeFields
     *
     * @return string[]|null
     */
    public function getCompositeFields()
    {
        return $this->container['compositeFields'];
    }

    /**
     * Sets compositeFields
     *
     * @param string[]|null $compositeFields An array of the fields that make up a composite field (e.g., address).
     *
     * @return self
     */
    public function setCompositeFields($compositeFields)
    {
        $this->container['compositeFields'] = $compositeFields;

        return $this;
    }

    /**
     * Gets summaryTableId
     *
     * @return string|null
     */
    public function getSummaryTableId()
    {
        return $this->container['summaryTableId'];
    }

    /**
     * Sets summaryTableId
     *
     * @param string|null $summaryTableId The table the summary field references fields from.
     *
     * @return self
     */
    public function setSummaryTableId($summaryTableId)
    {
        $this->container['summaryTableId'] = $summaryTableId;

        return $this;
    }

    /**
     * Gets displayTime
     *
     * @return bool|null
     */
    public function getDisplayTime()
    {
        return $this->container['displayTime'];
    }

    /**
     * Sets displayTime
     *
     * @param bool|null $displayTime Indicates whether to display the time, in addition to the date.
     *
     * @return self
     */
    public function setDisplayTime($displayTime)
    {
        $this->container['displayTime'] = $displayTime;

        return $this;
    }

    /**
     * Gets versionMode
     *
     * @return string|null
     */
    public function getVersionMode()
    {
        return $this->container['versionMode'];
    }

    /**
     * Sets versionMode
     *
     * @param string|null $versionMode Version modes for files. Keep all versions vs keep last version.
     *
     * @return self
     */
    public function setVersionMode($versionMode)
    {
        $allowedValues = $this->getVersionModeAllowableValues();
        if (!is_null($versionMode) && !in_array($versionMode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'versionMode', must be one of '%s'",
                    $versionMode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['versionMode'] = $versionMode;

        return $this;
    }

    /**
     * Gets snapFieldId
     *
     * @return int|null
     */
    public function getSnapFieldId()
    {
        return $this->container['snapFieldId'];
    }

    /**
     * Sets snapFieldId
     *
     * @param int|null $snapFieldId The id of the field that is used to snapshot values from, when applicable.
     *
     * @return self
     */
    public function setSnapFieldId($snapFieldId)
    {
        $this->container['snapFieldId'] = $snapFieldId;

        return $this;
    }

    /**
     * Gets hours24
     *
     * @return bool|null
     */
    public function getHours24()
    {
        return $this->container['hours24'];
    }

    /**
     * Sets hours24
     *
     * @param bool|null $hours24 Indicates whether or not to display time in the 24-hour format within the product.
     *
     * @return self
     */
    public function setHours24($hours24)
    {
        $this->container['hours24'] = $hours24;

        return $this;
    }

    /**
     * Gets sortAlpha
     *
     * @return bool|null
     */
    public function getSortAlpha()
    {
        return $this->container['sortAlpha'];
    }

    /**
     * Sets sortAlpha
     *
     * @param bool|null $sortAlpha Whether to sort alphabetically, default sort is by record ID.
     *
     * @return self
     */
    public function setSortAlpha($sortAlpha)
    {
        $this->container['sortAlpha'] = $sortAlpha;

        return $this;
    }

    /**
     * Gets sortAsGiven
     *
     * @return bool|null
     */
    public function getSortAsGiven()
    {
        return $this->container['sortAsGiven'];
    }

    /**
     * Sets sortAsGiven
     *
     * @param bool|null $sortAsGiven Indicates if the listed entries sort as entered vs alphabetically.
     *
     * @return self
     */
    public function setSortAsGiven($sortAsGiven)
    {
        $this->container['sortAsGiven'] = $sortAsGiven;

        return $this;
    }

    /**
     * Gets hasExtension
     *
     * @return bool|null
     */
    public function getHasExtension()
    {
        return $this->container['hasExtension'];
    }

    /**
     * Sets hasExtension
     *
     * @param bool|null $hasExtension Whether this field has a phone extension.
     *
     * @return self
     */
    public function setHasExtension($hasExtension)
    {
        $this->container['hasExtension'] = $hasExtension;

        return $this;
    }

    /**
     * Gets useNewWindow
     *
     * @return bool|null
     */
    public function getUseNewWindow()
    {
        return $this->container['useNewWindow'];
    }

    /**
     * Sets useNewWindow
     *
     * @param bool|null $useNewWindow Indicates if the URL should open a new window when a user clicks it within the product.
     *
     * @return self
     */
    public function setUseNewWindow($useNewWindow)
    {
        $this->container['useNewWindow'] = $useNewWindow;

        return $this;
    }

    /**
     * Gets appendOnly
     *
     * @return bool|null
     */
    public function getAppendOnly()
    {
        return $this->container['appendOnly'];
    }

    /**
     * Sets appendOnly
     *
     * @param bool|null $appendOnly Whether this field is append only.
     *
     * @return self
     */
    public function setAppendOnly($appendOnly)
    {
        $this->container['appendOnly'] = $appendOnly;

        return $this;
    }

    /**
     * Gets displayAsLink
     *
     * @return bool|null
     */
    public function getDisplayAsLink()
    {
        return $this->container['displayAsLink'];
    }

    /**
     * Sets displayAsLink
     *
     * @param bool|null $displayAsLink Indicates if a field that is part of the relationship should be shown as a hyperlink to the parent record within the product.
     *
     * @return self
     */
    public function setDisplayAsLink($displayAsLink)
    {
        $this->container['displayAsLink'] = $displayAsLink;

        return $this;
    }

    /**
     * Gets lookupReferenceFieldId
     *
     * @return int|null
     */
    public function getLookupReferenceFieldId()
    {
        return $this->container['lookupReferenceFieldId'];
    }

    /**
     * Sets lookupReferenceFieldId
     *
     * @param int|null $lookupReferenceFieldId The id of the field that is the reference in the relationship for this lookup.
     *
     * @return self
     */
    public function setLookupReferenceFieldId($lookupReferenceFieldId)
    {
        $this->container['lookupReferenceFieldId'] = $lookupReferenceFieldId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


