<?php
/**
 * InlineResponse2001Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Rossity\PhpQuickbase
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Quick Base API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Rossity\PhpQuickbase;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2001Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2001
 * @package     Rossity\PhpQuickbase
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse2001Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2001"
     */
    public function testInlineResponse2001()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "ownerId"
     */
    public function testPropertyOwnerId()
    {
    }

    /**
     * Test attribute "query"
     */
    public function testPropertyQuery()
    {
    }

    /**
     * Test attribute "properties"
     */
    public function testPropertyProperties()
    {
    }

    /**
     * Test attribute "usedLast"
     */
    public function testPropertyUsedLast()
    {
    }

    /**
     * Test attribute "usedCount"
     */
    public function testPropertyUsedCount()
    {
    }
}
