<?php
/**
 * AppsApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Rossity\PhpQuickbase
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Quick Base API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Rossity\PhpQuickbase\Test\Api;

use \Rossity\PhpQuickbase\Configuration;
use \Rossity\PhpQuickbase\ApiException;
use \Rossity\PhpQuickbase\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AppsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Rossity\PhpQuickbase
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AppsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for copyApp
     *
     * Copy an app.
     *
     */
    public function testCopyApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createApp
     *
     * Create an app.
     *
     */
    public function testCreateApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteApp
     *
     * Delete an app.
     *
     */
    public function testDeleteApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApp
     *
     * Get an app.
     *
     */
    public function testGetApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAppEvents
     *
     * Get app events.
     *
     */
    public function testGetAppEvents()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateApp
     *
     * Update an app.
     *
     */
    public function testUpdateApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
