<?php
/**
 * UserTokenApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Rossity\PhpQuickbase
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Quick Base API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Rossity\PhpQuickbase\Test\Api;

use \Rossity\PhpQuickbase\Configuration;
use \Rossity\PhpQuickbase\ApiException;
use \Rossity\PhpQuickbase\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UserTokenApiTest Class Doc Comment
 *
 * @category Class
 * @package  Rossity\PhpQuickbase
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserTokenApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cloneUserToken
     *
     * Clone a user token.
     *
     */
    public function testCloneUserToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deactivateUserToken
     *
     * Deactivate a user token.
     *
     */
    public function testDeactivateUserToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteUserToken
     *
     * Delete a user token.
     *
     */
    public function testDeleteUserToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
